/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class AAddressOfTerm extends PTerm
{
    private TAddressOf _addressOf_;
    private PRvalueVariable _rvalueVariable_;

    public AAddressOfTerm()
    {
        // Constructor
    }

    public AAddressOfTerm(
        @SuppressWarnings("hiding") TAddressOf _addressOf_,
        @SuppressWarnings("hiding") PRvalueVariable _rvalueVariable_)
    {
        // Constructor
        setAddressOf(_addressOf_);

        setRvalueVariable(_rvalueVariable_);

    }

    @Override
    public Object clone()
    {
        return new AAddressOfTerm(
            cloneNode(this._addressOf_),
            cloneNode(this._rvalueVariable_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddressOfTerm(this);
    }

    public TAddressOf getAddressOf()
    {
        return this._addressOf_;
    }

    public void setAddressOf(TAddressOf node)
    {
        if(this._addressOf_ != null)
        {
            this._addressOf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addressOf_ = node;
    }

    public PRvalueVariable getRvalueVariable()
    {
        return this._rvalueVariable_;
    }

    public void setRvalueVariable(PRvalueVariable node)
    {
        if(this._rvalueVariable_ != null)
        {
            this._rvalueVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rvalueVariable_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._addressOf_)
            + toString(this._rvalueVariable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._addressOf_ == child)
        {
            this._addressOf_ = null;
            return;
        }

        if(this._rvalueVariable_ == child)
        {
            this._rvalueVariable_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._addressOf_ == oldChild)
        {
            setAddressOf((TAddressOf) newChild);
            return;
        }

        if(this._rvalueVariable_ == oldChild)
        {
            setRvalueVariable((PRvalueVariable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
