/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class AAssignmentExpressionStatement extends PExpressionStatement
{
    private PExpressionLvalue _expressionLvalue_;
    private PAssignmentOp _assignmentOp_;
    private PExpressionRvalue _expressionRvalue_;
    private PSeparator _separator_;

    public AAssignmentExpressionStatement()
    {
        // Constructor
    }

    public AAssignmentExpressionStatement(
        @SuppressWarnings("hiding") PExpressionLvalue _expressionLvalue_,
        @SuppressWarnings("hiding") PAssignmentOp _assignmentOp_,
        @SuppressWarnings("hiding") PExpressionRvalue _expressionRvalue_,
        @SuppressWarnings("hiding") PSeparator _separator_)
    {
        // Constructor
        setExpressionLvalue(_expressionLvalue_);

        setAssignmentOp(_assignmentOp_);

        setExpressionRvalue(_expressionRvalue_);

        setSeparator(_separator_);

    }

    @Override
    public Object clone()
    {
        return new AAssignmentExpressionStatement(
            cloneNode(this._expressionLvalue_),
            cloneNode(this._assignmentOp_),
            cloneNode(this._expressionRvalue_),
            cloneNode(this._separator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignmentExpressionStatement(this);
    }

    public PExpressionLvalue getExpressionLvalue()
    {
        return this._expressionLvalue_;
    }

    public void setExpressionLvalue(PExpressionLvalue node)
    {
        if(this._expressionLvalue_ != null)
        {
            this._expressionLvalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvalue_ = node;
    }

    public PAssignmentOp getAssignmentOp()
    {
        return this._assignmentOp_;
    }

    public void setAssignmentOp(PAssignmentOp node)
    {
        if(this._assignmentOp_ != null)
        {
            this._assignmentOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignmentOp_ = node;
    }

    public PExpressionRvalue getExpressionRvalue()
    {
        return this._expressionRvalue_;
    }

    public void setExpressionRvalue(PExpressionRvalue node)
    {
        if(this._expressionRvalue_ != null)
        {
            this._expressionRvalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionRvalue_ = node;
    }

    public PSeparator getSeparator()
    {
        return this._separator_;
    }

    public void setSeparator(PSeparator node)
    {
        if(this._separator_ != null)
        {
            this._separator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvalue_)
            + toString(this._assignmentOp_)
            + toString(this._expressionRvalue_)
            + toString(this._separator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvalue_ == child)
        {
            this._expressionLvalue_ = null;
            return;
        }

        if(this._assignmentOp_ == child)
        {
            this._assignmentOp_ = null;
            return;
        }

        if(this._expressionRvalue_ == child)
        {
            this._expressionRvalue_ = null;
            return;
        }

        if(this._separator_ == child)
        {
            this._separator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvalue_ == oldChild)
        {
            setExpressionLvalue((PExpressionLvalue) newChild);
            return;
        }

        if(this._assignmentOp_ == oldChild)
        {
            setAssignmentOp((PAssignmentOp) newChild);
            return;
        }

        if(this._expressionRvalue_ == oldChild)
        {
            setExpressionRvalue((PExpressionRvalue) newChild);
            return;
        }

        if(this._separator_ == oldChild)
        {
            setSeparator((PSeparator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
