/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ABasicInitializationExpression extends PInitializationExpression
{
    private PExpressionRvalue _expressionRvalue_;

    public ABasicInitializationExpression()
    {
        // Constructor
    }

    public ABasicInitializationExpression(
        @SuppressWarnings("hiding") PExpressionRvalue _expressionRvalue_)
    {
        // Constructor
        setExpressionRvalue(_expressionRvalue_);

    }

    @Override
    public Object clone()
    {
        return new ABasicInitializationExpression(
            cloneNode(this._expressionRvalue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABasicInitializationExpression(this);
    }

    public PExpressionRvalue getExpressionRvalue()
    {
        return this._expressionRvalue_;
    }

    public void setExpressionRvalue(PExpressionRvalue node)
    {
        if(this._expressionRvalue_ != null)
        {
            this._expressionRvalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionRvalue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionRvalue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionRvalue_ == child)
        {
            this._expressionRvalue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionRvalue_ == oldChild)
        {
            setExpressionRvalue((PExpressionRvalue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
