/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ABindingRawPattern extends PRawPattern
{
    private PBindingPattern _bindingPattern_;

    public ABindingRawPattern()
    {
        // Constructor
    }

    public ABindingRawPattern(
        @SuppressWarnings("hiding") PBindingPattern _bindingPattern_)
    {
        // Constructor
        setBindingPattern(_bindingPattern_);

    }

    @Override
    public Object clone()
    {
        return new ABindingRawPattern(
            cloneNode(this._bindingPattern_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABindingRawPattern(this);
    }

    public PBindingPattern getBindingPattern()
    {
        return this._bindingPattern_;
    }

    public void setBindingPattern(PBindingPattern node)
    {
        if(this._bindingPattern_ != null)
        {
            this._bindingPattern_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bindingPattern_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bindingPattern_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bindingPattern_ == child)
        {
            this._bindingPattern_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bindingPattern_ == oldChild)
        {
            setBindingPattern((PBindingPattern) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
