/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ABinaryBraceComparativeExpression extends PBraceComparativeExpression
{
    private PBraceComparativeExpression _braceComparativeExpression_;
    private PComparativeBinaryOp _comparativeBinaryOp_;
    private PBraceAdditiveExpression _braceAdditiveExpression_;

    public ABinaryBraceComparativeExpression()
    {
        // Constructor
    }

    public ABinaryBraceComparativeExpression(
        @SuppressWarnings("hiding") PBraceComparativeExpression _braceComparativeExpression_,
        @SuppressWarnings("hiding") PComparativeBinaryOp _comparativeBinaryOp_,
        @SuppressWarnings("hiding") PBraceAdditiveExpression _braceAdditiveExpression_)
    {
        // Constructor
        setBraceComparativeExpression(_braceComparativeExpression_);

        setComparativeBinaryOp(_comparativeBinaryOp_);

        setBraceAdditiveExpression(_braceAdditiveExpression_);

    }

    @Override
    public Object clone()
    {
        return new ABinaryBraceComparativeExpression(
            cloneNode(this._braceComparativeExpression_),
            cloneNode(this._comparativeBinaryOp_),
            cloneNode(this._braceAdditiveExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABinaryBraceComparativeExpression(this);
    }

    public PBraceComparativeExpression getBraceComparativeExpression()
    {
        return this._braceComparativeExpression_;
    }

    public void setBraceComparativeExpression(PBraceComparativeExpression node)
    {
        if(this._braceComparativeExpression_ != null)
        {
            this._braceComparativeExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._braceComparativeExpression_ = node;
    }

    public PComparativeBinaryOp getComparativeBinaryOp()
    {
        return this._comparativeBinaryOp_;
    }

    public void setComparativeBinaryOp(PComparativeBinaryOp node)
    {
        if(this._comparativeBinaryOp_ != null)
        {
            this._comparativeBinaryOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparativeBinaryOp_ = node;
    }

    public PBraceAdditiveExpression getBraceAdditiveExpression()
    {
        return this._braceAdditiveExpression_;
    }

    public void setBraceAdditiveExpression(PBraceAdditiveExpression node)
    {
        if(this._braceAdditiveExpression_ != null)
        {
            this._braceAdditiveExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._braceAdditiveExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._braceComparativeExpression_)
            + toString(this._comparativeBinaryOp_)
            + toString(this._braceAdditiveExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._braceComparativeExpression_ == child)
        {
            this._braceComparativeExpression_ = null;
            return;
        }

        if(this._comparativeBinaryOp_ == child)
        {
            this._comparativeBinaryOp_ = null;
            return;
        }

        if(this._braceAdditiveExpression_ == child)
        {
            this._braceAdditiveExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._braceComparativeExpression_ == oldChild)
        {
            setBraceComparativeExpression((PBraceComparativeExpression) newChild);
            return;
        }

        if(this._comparativeBinaryOp_ == oldChild)
        {
            setComparativeBinaryOp((PComparativeBinaryOp) newChild);
            return;
        }

        if(this._braceAdditiveExpression_ == oldChild)
        {
            setBraceAdditiveExpression((PBraceAdditiveExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
