/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class AClosureBraceExpression extends PBraceExpression
{
    private PClosureDeclaratorList _closureDeclaratorList_;
    private PBraceExpression _braceExpression_;

    public AClosureBraceExpression()
    {
        // Constructor
    }

    public AClosureBraceExpression(
        @SuppressWarnings("hiding") PClosureDeclaratorList _closureDeclaratorList_,
        @SuppressWarnings("hiding") PBraceExpression _braceExpression_)
    {
        // Constructor
        setClosureDeclaratorList(_closureDeclaratorList_);

        setBraceExpression(_braceExpression_);

    }

    @Override
    public Object clone()
    {
        return new AClosureBraceExpression(
            cloneNode(this._closureDeclaratorList_),
            cloneNode(this._braceExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClosureBraceExpression(this);
    }

    public PClosureDeclaratorList getClosureDeclaratorList()
    {
        return this._closureDeclaratorList_;
    }

    public void setClosureDeclaratorList(PClosureDeclaratorList node)
    {
        if(this._closureDeclaratorList_ != null)
        {
            this._closureDeclaratorList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closureDeclaratorList_ = node;
    }

    public PBraceExpression getBraceExpression()
    {
        return this._braceExpression_;
    }

    public void setBraceExpression(PBraceExpression node)
    {
        if(this._braceExpression_ != null)
        {
            this._braceExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._braceExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._closureDeclaratorList_)
            + toString(this._braceExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._closureDeclaratorList_ == child)
        {
            this._closureDeclaratorList_ = null;
            return;
        }

        if(this._braceExpression_ == child)
        {
            this._braceExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._closureDeclaratorList_ == oldChild)
        {
            setClosureDeclaratorList((PClosureDeclaratorList) newChild);
            return;
        }

        if(this._braceExpression_ == oldChild)
        {
            setBraceExpression((PBraceExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
