/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class AConditionalSection extends PConditionalSection
{
    private TConditionalBranchKeyword _conditionalBranchKeyword_;
    private PBraceExpression _braceExpression_;
    private TLBrace _lBrace_;
    private PScopedBody _scopedBody_;
    private TRBrace _rBrace_;
    private PElseSection _elseSection_;

    public AConditionalSection()
    {
        // Constructor
    }

    public AConditionalSection(
        @SuppressWarnings("hiding") TConditionalBranchKeyword _conditionalBranchKeyword_,
        @SuppressWarnings("hiding") PBraceExpression _braceExpression_,
        @SuppressWarnings("hiding") TLBrace _lBrace_,
        @SuppressWarnings("hiding") PScopedBody _scopedBody_,
        @SuppressWarnings("hiding") TRBrace _rBrace_,
        @SuppressWarnings("hiding") PElseSection _elseSection_)
    {
        // Constructor
        setConditionalBranchKeyword(_conditionalBranchKeyword_);

        setBraceExpression(_braceExpression_);

        setLBrace(_lBrace_);

        setScopedBody(_scopedBody_);

        setRBrace(_rBrace_);

        setElseSection(_elseSection_);

    }

    @Override
    public Object clone()
    {
        return new AConditionalSection(
            cloneNode(this._conditionalBranchKeyword_),
            cloneNode(this._braceExpression_),
            cloneNode(this._lBrace_),
            cloneNode(this._scopedBody_),
            cloneNode(this._rBrace_),
            cloneNode(this._elseSection_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConditionalSection(this);
    }

    public TConditionalBranchKeyword getConditionalBranchKeyword()
    {
        return this._conditionalBranchKeyword_;
    }

    public void setConditionalBranchKeyword(TConditionalBranchKeyword node)
    {
        if(this._conditionalBranchKeyword_ != null)
        {
            this._conditionalBranchKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionalBranchKeyword_ = node;
    }

    public PBraceExpression getBraceExpression()
    {
        return this._braceExpression_;
    }

    public void setBraceExpression(PBraceExpression node)
    {
        if(this._braceExpression_ != null)
        {
            this._braceExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._braceExpression_ = node;
    }

    public TLBrace getLBrace()
    {
        return this._lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(this._lBrace_ != null)
        {
            this._lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrace_ = node;
    }

    public PScopedBody getScopedBody()
    {
        return this._scopedBody_;
    }

    public void setScopedBody(PScopedBody node)
    {
        if(this._scopedBody_ != null)
        {
            this._scopedBody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._scopedBody_ = node;
    }

    public TRBrace getRBrace()
    {
        return this._rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(this._rBrace_ != null)
        {
            this._rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrace_ = node;
    }

    public PElseSection getElseSection()
    {
        return this._elseSection_;
    }

    public void setElseSection(PElseSection node)
    {
        if(this._elseSection_ != null)
        {
            this._elseSection_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elseSection_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditionalBranchKeyword_)
            + toString(this._braceExpression_)
            + toString(this._lBrace_)
            + toString(this._scopedBody_)
            + toString(this._rBrace_)
            + toString(this._elseSection_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditionalBranchKeyword_ == child)
        {
            this._conditionalBranchKeyword_ = null;
            return;
        }

        if(this._braceExpression_ == child)
        {
            this._braceExpression_ = null;
            return;
        }

        if(this._lBrace_ == child)
        {
            this._lBrace_ = null;
            return;
        }

        if(this._scopedBody_ == child)
        {
            this._scopedBody_ = null;
            return;
        }

        if(this._rBrace_ == child)
        {
            this._rBrace_ = null;
            return;
        }

        if(this._elseSection_ == child)
        {
            this._elseSection_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditionalBranchKeyword_ == oldChild)
        {
            setConditionalBranchKeyword((TConditionalBranchKeyword) newChild);
            return;
        }

        if(this._braceExpression_ == oldChild)
        {
            setBraceExpression((PBraceExpression) newChild);
            return;
        }

        if(this._lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        if(this._scopedBody_ == oldChild)
        {
            setScopedBody((PScopedBody) newChild);
            return;
        }

        if(this._rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

        if(this._elseSection_ == oldChild)
        {
            setElseSection((PElseSection) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
