/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ADereferencedNonAddressVariable extends PNonAddressVariable
{
    private TDereference _dereference_;
    private PVariable _variable_;

    public ADereferencedNonAddressVariable()
    {
        // Constructor
    }

    public ADereferencedNonAddressVariable(
        @SuppressWarnings("hiding") TDereference _dereference_,
        @SuppressWarnings("hiding") PVariable _variable_)
    {
        // Constructor
        setDereference(_dereference_);

        setVariable(_variable_);

    }

    @Override
    public Object clone()
    {
        return new ADereferencedNonAddressVariable(
            cloneNode(this._dereference_),
            cloneNode(this._variable_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADereferencedNonAddressVariable(this);
    }

    public TDereference getDereference()
    {
        return this._dereference_;
    }

    public void setDereference(TDereference node)
    {
        if(this._dereference_ != null)
        {
            this._dereference_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dereference_ = node;
    }

    public PVariable getVariable()
    {
        return this._variable_;
    }

    public void setVariable(PVariable node)
    {
        if(this._variable_ != null)
        {
            this._variable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variable_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dereference_)
            + toString(this._variable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dereference_ == child)
        {
            this._dereference_ = null;
            return;
        }

        if(this._variable_ == child)
        {
            this._variable_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dereference_ == oldChild)
        {
            setDereference((TDereference) newChild);
            return;
        }

        if(this._variable_ == oldChild)
        {
            setVariable((PVariable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
