/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ADivideAssignmentOp extends PAssignmentOp
{
    private TDivideEquals _divideEquals_;

    public ADivideAssignmentOp()
    {
        // Constructor
    }

    public ADivideAssignmentOp(
        @SuppressWarnings("hiding") TDivideEquals _divideEquals_)
    {
        // Constructor
        setDivideEquals(_divideEquals_);

    }

    @Override
    public Object clone()
    {
        return new ADivideAssignmentOp(
            cloneNode(this._divideEquals_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivideAssignmentOp(this);
    }

    public TDivideEquals getDivideEquals()
    {
        return this._divideEquals_;
    }

    public void setDivideEquals(TDivideEquals node)
    {
        if(this._divideEquals_ != null)
        {
            this._divideEquals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._divideEquals_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._divideEquals_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._divideEquals_ == child)
        {
            this._divideEquals_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._divideEquals_ == oldChild)
        {
            setDivideEquals((TDivideEquals) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
