/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ALogicalOrClosurePatternList extends PClosurePatternList
{
    private TLogicalOr _logicalOr_;

    public ALogicalOrClosurePatternList()
    {
        // Constructor
    }

    public ALogicalOrClosurePatternList(
        @SuppressWarnings("hiding") TLogicalOr _logicalOr_)
    {
        // Constructor
        setLogicalOr(_logicalOr_);

    }

    @Override
    public Object clone()
    {
        return new ALogicalOrClosurePatternList(
            cloneNode(this._logicalOr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogicalOrClosurePatternList(this);
    }

    public TLogicalOr getLogicalOr()
    {
        return this._logicalOr_;
    }

    public void setLogicalOr(TLogicalOr node)
    {
        if(this._logicalOr_ != null)
        {
            this._logicalOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicalOr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicalOr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicalOr_ == child)
        {
            this._logicalOr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicalOr_ == oldChild)
        {
            setLogicalOr((TLogicalOr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
