/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class AMethodDefinitionGeneralSection extends PGeneralSection
{
    private PMethodDefinition _methodDefinition_;

    public AMethodDefinitionGeneralSection()
    {
        // Constructor
    }

    public AMethodDefinitionGeneralSection(
        @SuppressWarnings("hiding") PMethodDefinition _methodDefinition_)
    {
        // Constructor
        setMethodDefinition(_methodDefinition_);

    }

    @Override
    public Object clone()
    {
        return new AMethodDefinitionGeneralSection(
            cloneNode(this._methodDefinition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodDefinitionGeneralSection(this);
    }

    public PMethodDefinition getMethodDefinition()
    {
        return this._methodDefinition_;
    }

    public void setMethodDefinition(PMethodDefinition node)
    {
        if(this._methodDefinition_ != null)
        {
            this._methodDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodDefinition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._methodDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._methodDefinition_ == child)
        {
            this._methodDefinition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._methodDefinition_ == oldChild)
        {
            setMethodDefinition((PMethodDefinition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
