/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class AMinusAssignmentOp extends PAssignmentOp
{
    private TMinusEquals _minusEquals_;

    public AMinusAssignmentOp()
    {
        // Constructor
    }

    public AMinusAssignmentOp(
        @SuppressWarnings("hiding") TMinusEquals _minusEquals_)
    {
        // Constructor
        setMinusEquals(_minusEquals_);

    }

    @Override
    public Object clone()
    {
        return new AMinusAssignmentOp(
            cloneNode(this._minusEquals_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusAssignmentOp(this);
    }

    public TMinusEquals getMinusEquals()
    {
        return this._minusEquals_;
    }

    public void setMinusEquals(TMinusEquals node)
    {
        if(this._minusEquals_ != null)
        {
            this._minusEquals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusEquals_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minusEquals_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minusEquals_ == child)
        {
            this._minusEquals_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minusEquals_ == oldChild)
        {
            setMinusEquals((TMinusEquals) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
