/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ANoInitialisationVariableDeclaration extends PVariableDeclaration
{
    private TVar _var_;
    private PLvalueVariable _lvalueVariable_;
    private TSemicolon _semicolon_;

    public ANoInitialisationVariableDeclaration()
    {
        // Constructor
    }

    public ANoInitialisationVariableDeclaration(
        @SuppressWarnings("hiding") TVar _var_,
        @SuppressWarnings("hiding") PLvalueVariable _lvalueVariable_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setVar(_var_);

        setLvalueVariable(_lvalueVariable_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new ANoInitialisationVariableDeclaration(
            cloneNode(this._var_),
            cloneNode(this._lvalueVariable_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoInitialisationVariableDeclaration(this);
    }

    public TVar getVar()
    {
        return this._var_;
    }

    public void setVar(TVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PLvalueVariable getLvalueVariable()
    {
        return this._lvalueVariable_;
    }

    public void setLvalueVariable(PLvalueVariable node)
    {
        if(this._lvalueVariable_ != null)
        {
            this._lvalueVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lvalueVariable_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._lvalueVariable_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._lvalueVariable_ == child)
        {
            this._lvalueVariable_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((TVar) newChild);
            return;
        }

        if(this._lvalueVariable_ == oldChild)
        {
            setLvalueVariable((PLvalueVariable) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
