/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import java.util.*;
import drlc.analysis.*;

@SuppressWarnings("nls")
public final class AParameterDeclarator extends PParameterDeclarator
{
    private final LinkedList<TVariableModifier> _variableModifier_ = new LinkedList<TVariableModifier>();
    private PIdentifier _identifier_;
    private PTypeAnnotation _typeAnnotation_;

    public AParameterDeclarator()
    {
        // Constructor
    }

    public AParameterDeclarator(
        @SuppressWarnings("hiding") List<?> _variableModifier_,
        @SuppressWarnings("hiding") PIdentifier _identifier_,
        @SuppressWarnings("hiding") PTypeAnnotation _typeAnnotation_)
    {
        // Constructor
        setVariableModifier(_variableModifier_);

        setIdentifier(_identifier_);

        setTypeAnnotation(_typeAnnotation_);

    }

    @Override
    public Object clone()
    {
        return new AParameterDeclarator(
            cloneList(this._variableModifier_),
            cloneNode(this._identifier_),
            cloneNode(this._typeAnnotation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParameterDeclarator(this);
    }

    public LinkedList<TVariableModifier> getVariableModifier()
    {
        return this._variableModifier_;
    }

    public void setVariableModifier(List<?> list)
    {
        for(TVariableModifier e : this._variableModifier_)
        {
            e.parent(null);
        }
        this._variableModifier_.clear();

        for(Object obj_e : list)
        {
            TVariableModifier e = (TVariableModifier) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._variableModifier_.add(e);
        }
    }

    public PIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(PIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PTypeAnnotation getTypeAnnotation()
    {
        return this._typeAnnotation_;
    }

    public void setTypeAnnotation(PTypeAnnotation node)
    {
        if(this._typeAnnotation_ != null)
        {
            this._typeAnnotation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeAnnotation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variableModifier_)
            + toString(this._identifier_)
            + toString(this._typeAnnotation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variableModifier_.remove(child))
        {
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._typeAnnotation_ == child)
        {
            this._typeAnnotation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TVariableModifier> i = this._variableModifier_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TVariableModifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((PIdentifier) newChild);
            return;
        }

        if(this._typeAnnotation_ == oldChild)
        {
            setTypeAnnotation((PTypeAnnotation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
