/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class AParameterListTail extends PParameterListTail
{
    private TComma _comma_;
    private PNonAddressVariable _nonAddressVariable_;

    public AParameterListTail()
    {
        // Constructor
    }

    public AParameterListTail(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PNonAddressVariable _nonAddressVariable_)
    {
        // Constructor
        setComma(_comma_);

        setNonAddressVariable(_nonAddressVariable_);

    }

    @Override
    public Object clone()
    {
        return new AParameterListTail(
            cloneNode(this._comma_),
            cloneNode(this._nonAddressVariable_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParameterListTail(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PNonAddressVariable getNonAddressVariable()
    {
        return this._nonAddressVariable_;
    }

    public void setNonAddressVariable(PNonAddressVariable node)
    {
        if(this._nonAddressVariable_ != null)
        {
            this._nonAddressVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nonAddressVariable_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._nonAddressVariable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._nonAddressVariable_ == child)
        {
            this._nonAddressVariable_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._nonAddressVariable_ == oldChild)
        {
            setNonAddressVariable((PNonAddressVariable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
