/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import java.util.*;
import drlc.analysis.*;

@SuppressWarnings("nls")
public final class APatternList extends PPatternList
{
    private PPattern _pattern_;
    private final LinkedList<PPatternListTail> _patternListTail_ = new LinkedList<PPatternListTail>();
    private TComma _comma_;

    public APatternList()
    {
        // Constructor
    }

    public APatternList(
        @SuppressWarnings("hiding") PPattern _pattern_,
        @SuppressWarnings("hiding") List<?> _patternListTail_,
        @SuppressWarnings("hiding") TComma _comma_)
    {
        // Constructor
        setPattern(_pattern_);

        setPatternListTail(_patternListTail_);

        setComma(_comma_);

    }

    @Override
    public Object clone()
    {
        return new APatternList(
            cloneNode(this._pattern_),
            cloneList(this._patternListTail_),
            cloneNode(this._comma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPatternList(this);
    }

    public PPattern getPattern()
    {
        return this._pattern_;
    }

    public void setPattern(PPattern node)
    {
        if(this._pattern_ != null)
        {
            this._pattern_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pattern_ = node;
    }

    public LinkedList<PPatternListTail> getPatternListTail()
    {
        return this._patternListTail_;
    }

    public void setPatternListTail(List<?> list)
    {
        for(PPatternListTail e : this._patternListTail_)
        {
            e.parent(null);
        }
        this._patternListTail_.clear();

        for(Object obj_e : list)
        {
            PPatternListTail e = (PPatternListTail) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._patternListTail_.add(e);
        }
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pattern_)
            + toString(this._patternListTail_)
            + toString(this._comma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pattern_ == child)
        {
            this._pattern_ = null;
            return;
        }

        if(this._patternListTail_.remove(child))
        {
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pattern_ == oldChild)
        {
            setPattern((PPattern) newChild);
            return;
        }

        for(ListIterator<PPatternListTail> i = this._patternListTail_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPatternListTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
