/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class APrioritizedExpression extends PExpression
{
    private PPrioritizedExpression _prioritizedExpression_;

    public APrioritizedExpression()
    {
        // Constructor
    }

    public APrioritizedExpression(
        @SuppressWarnings("hiding") PPrioritizedExpression _prioritizedExpression_)
    {
        // Constructor
        setPrioritizedExpression(_prioritizedExpression_);

    }

    @Override
    public Object clone()
    {
        return new APrioritizedExpression(
            cloneNode(this._prioritizedExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrioritizedExpression(this);
    }

    public PPrioritizedExpression getPrioritizedExpression()
    {
        return this._prioritizedExpression_;
    }

    public void setPrioritizedExpression(PPrioritizedExpression node)
    {
        if(this._prioritizedExpression_ != null)
        {
            this._prioritizedExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prioritizedExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prioritizedExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prioritizedExpression_ == child)
        {
            this._prioritizedExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prioritizedExpression_ == oldChild)
        {
            setPrioritizedExpression((PPrioritizedExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
