/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class APrioritizedBraceShiftExpression extends PBraceShiftExpression
{
    private PBraceUnaryExpression _braceUnaryExpression_;

    public APrioritizedBraceShiftExpression()
    {
        // Constructor
    }

    public APrioritizedBraceShiftExpression(
        @SuppressWarnings("hiding") PBraceUnaryExpression _braceUnaryExpression_)
    {
        // Constructor
        setBraceUnaryExpression(_braceUnaryExpression_);

    }

    @Override
    public Object clone()
    {
        return new APrioritizedBraceShiftExpression(
            cloneNode(this._braceUnaryExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrioritizedBraceShiftExpression(this);
    }

    public PBraceUnaryExpression getBraceUnaryExpression()
    {
        return this._braceUnaryExpression_;
    }

    public void setBraceUnaryExpression(PBraceUnaryExpression node)
    {
        if(this._braceUnaryExpression_ != null)
        {
            this._braceUnaryExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._braceUnaryExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._braceUnaryExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._braceUnaryExpression_ == child)
        {
            this._braceUnaryExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._braceUnaryExpression_ == oldChild)
        {
            setBraceUnaryExpression((PBraceUnaryExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
