/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class APrioritizedConditionEqualityExpression extends PConditionEqualityExpression
{
    private PConditionComparativeExpression _conditionComparativeExpression_;

    public APrioritizedConditionEqualityExpression()
    {
        // Constructor
    }

    public APrioritizedConditionEqualityExpression(
        @SuppressWarnings("hiding") PConditionComparativeExpression _conditionComparativeExpression_)
    {
        // Constructor
        setConditionComparativeExpression(_conditionComparativeExpression_);

    }

    @Override
    public Object clone()
    {
        return new APrioritizedConditionEqualityExpression(
            cloneNode(this._conditionComparativeExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrioritizedConditionEqualityExpression(this);
    }

    public PConditionComparativeExpression getConditionComparativeExpression()
    {
        return this._conditionComparativeExpression_;
    }

    public void setConditionComparativeExpression(PConditionComparativeExpression node)
    {
        if(this._conditionComparativeExpression_ != null)
        {
            this._conditionComparativeExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionComparativeExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditionComparativeExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditionComparativeExpression_ == child)
        {
            this._conditionComparativeExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditionComparativeExpression_ == oldChild)
        {
            setConditionComparativeExpression((PConditionComparativeExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
