/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class APrioritizedConditionComparativeExpression extends PConditionComparativeExpression
{
    private PConditionAdditiveExpression _conditionAdditiveExpression_;

    public APrioritizedConditionComparativeExpression()
    {
        // Constructor
    }

    public APrioritizedConditionComparativeExpression(
        @SuppressWarnings("hiding") PConditionAdditiveExpression _conditionAdditiveExpression_)
    {
        // Constructor
        setConditionAdditiveExpression(_conditionAdditiveExpression_);

    }

    @Override
    public Object clone()
    {
        return new APrioritizedConditionComparativeExpression(
            cloneNode(this._conditionAdditiveExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrioritizedConditionComparativeExpression(this);
    }

    public PConditionAdditiveExpression getConditionAdditiveExpression()
    {
        return this._conditionAdditiveExpression_;
    }

    public void setConditionAdditiveExpression(PConditionAdditiveExpression node)
    {
        if(this._conditionAdditiveExpression_ != null)
        {
            this._conditionAdditiveExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionAdditiveExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditionAdditiveExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditionAdditiveExpression_ == child)
        {
            this._conditionAdditiveExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditionAdditiveExpression_ == oldChild)
        {
            setConditionAdditiveExpression((PConditionAdditiveExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
