/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class APrioritizedConditionalExpression3 extends PConditionalExpression3
{
    private PConditionalExpression4 _conditionalExpression4_;

    public APrioritizedConditionalExpression3()
    {
        // Constructor
    }

    public APrioritizedConditionalExpression3(
        @SuppressWarnings("hiding") PConditionalExpression4 _conditionalExpression4_)
    {
        // Constructor
        setConditionalExpression4(_conditionalExpression4_);

    }

    @Override
    public Object clone()
    {
        return new APrioritizedConditionalExpression3(
            cloneNode(this._conditionalExpression4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrioritizedConditionalExpression3(this);
    }

    public PConditionalExpression4 getConditionalExpression4()
    {
        return this._conditionalExpression4_;
    }

    public void setConditionalExpression4(PConditionalExpression4 node)
    {
        if(this._conditionalExpression4_ != null)
        {
            this._conditionalExpression4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionalExpression4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditionalExpression4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditionalExpression4_ == child)
        {
            this._conditionalExpression4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditionalExpression4_ == oldChild)
        {
            setConditionalExpression4((PConditionalExpression4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
