/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ARightShiftAssignmentOp extends PAssignmentOp
{
    private TRightShiftEquals _rightShiftEquals_;

    public ARightShiftAssignmentOp()
    {
        // Constructor
    }

    public ARightShiftAssignmentOp(
        @SuppressWarnings("hiding") TRightShiftEquals _rightShiftEquals_)
    {
        // Constructor
        setRightShiftEquals(_rightShiftEquals_);

    }

    @Override
    public Object clone()
    {
        return new ARightShiftAssignmentOp(
            cloneNode(this._rightShiftEquals_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARightShiftAssignmentOp(this);
    }

    public TRightShiftEquals getRightShiftEquals()
    {
        return this._rightShiftEquals_;
    }

    public void setRightShiftEquals(TRightShiftEquals node)
    {
        if(this._rightShiftEquals_ != null)
        {
            this._rightShiftEquals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightShiftEquals_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rightShiftEquals_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rightShiftEquals_ == child)
        {
            this._rightShiftEquals_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rightShiftEquals_ == oldChild)
        {
            setRightShiftEquals((TRightShiftEquals) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
