/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ATernaryBraceTernaryExpression extends PBraceTernaryExpression
{
    private PBraceCastExpression _braceCastExpression_;
    private TQuestionMark _questionMark_;
    private PExpression _expression_;
    private TColon _colon_;
    private PBraceTernaryExpression _braceTernaryExpression_;

    public ATernaryBraceTernaryExpression()
    {
        // Constructor
    }

    public ATernaryBraceTernaryExpression(
        @SuppressWarnings("hiding") PBraceCastExpression _braceCastExpression_,
        @SuppressWarnings("hiding") TQuestionMark _questionMark_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PBraceTernaryExpression _braceTernaryExpression_)
    {
        // Constructor
        setBraceCastExpression(_braceCastExpression_);

        setQuestionMark(_questionMark_);

        setExpression(_expression_);

        setColon(_colon_);

        setBraceTernaryExpression(_braceTernaryExpression_);

    }

    @Override
    public Object clone()
    {
        return new ATernaryBraceTernaryExpression(
            cloneNode(this._braceCastExpression_),
            cloneNode(this._questionMark_),
            cloneNode(this._expression_),
            cloneNode(this._colon_),
            cloneNode(this._braceTernaryExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATernaryBraceTernaryExpression(this);
    }

    public PBraceCastExpression getBraceCastExpression()
    {
        return this._braceCastExpression_;
    }

    public void setBraceCastExpression(PBraceCastExpression node)
    {
        if(this._braceCastExpression_ != null)
        {
            this._braceCastExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._braceCastExpression_ = node;
    }

    public TQuestionMark getQuestionMark()
    {
        return this._questionMark_;
    }

    public void setQuestionMark(TQuestionMark node)
    {
        if(this._questionMark_ != null)
        {
            this._questionMark_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._questionMark_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PBraceTernaryExpression getBraceTernaryExpression()
    {
        return this._braceTernaryExpression_;
    }

    public void setBraceTernaryExpression(PBraceTernaryExpression node)
    {
        if(this._braceTernaryExpression_ != null)
        {
            this._braceTernaryExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._braceTernaryExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._braceCastExpression_)
            + toString(this._questionMark_)
            + toString(this._expression_)
            + toString(this._colon_)
            + toString(this._braceTernaryExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._braceCastExpression_ == child)
        {
            this._braceCastExpression_ = null;
            return;
        }

        if(this._questionMark_ == child)
        {
            this._questionMark_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._braceTernaryExpression_ == child)
        {
            this._braceTernaryExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._braceCastExpression_ == oldChild)
        {
            setBraceCastExpression((PBraceCastExpression) newChild);
            return;
        }

        if(this._questionMark_ == oldChild)
        {
            setQuestionMark((TQuestionMark) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._braceTernaryExpression_ == oldChild)
        {
            setBraceTernaryExpression((PBraceTernaryExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
