/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ATupleStructRawPattern extends PRawPattern
{
    private PPath _path_;
    private TLPar _lPar_;
    private PPatternList _patternList_;
    private TRPar _rPar_;

    public ATupleStructRawPattern()
    {
        // Constructor
    }

    public ATupleStructRawPattern(
        @SuppressWarnings("hiding") PPath _path_,
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PPatternList _patternList_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setPath(_path_);

        setLPar(_lPar_);

        setPatternList(_patternList_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new ATupleStructRawPattern(
            cloneNode(this._path_),
            cloneNode(this._lPar_),
            cloneNode(this._patternList_),
            cloneNode(this._rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATupleStructRawPattern(this);
    }

    public PPath getPath()
    {
        return this._path_;
    }

    public void setPath(PPath node)
    {
        if(this._path_ != null)
        {
            this._path_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._path_ = node;
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PPatternList getPatternList()
    {
        return this._patternList_;
    }

    public void setPatternList(PPatternList node)
    {
        if(this._patternList_ != null)
        {
            this._patternList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._patternList_ = node;
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._path_)
            + toString(this._lPar_)
            + toString(this._patternList_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._path_ == child)
        {
            this._path_ = null;
            return;
        }

        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._patternList_ == child)
        {
            this._patternList_ = null;
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._path_ == oldChild)
        {
            setPath((PPath) newChild);
            return;
        }

        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._patternList_ == oldChild)
        {
            setPatternList((PPatternList) newChild);
            return;
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
