/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ATupleRawPattern extends PRawPattern
{
    private TLPar _lPar_;
    private PTuplePatternList _tuplePatternList_;
    private TRPar _rPar_;

    public ATupleRawPattern()
    {
        // Constructor
    }

    public ATupleRawPattern(
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PTuplePatternList _tuplePatternList_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setLPar(_lPar_);

        setTuplePatternList(_tuplePatternList_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new ATupleRawPattern(
            cloneNode(this._lPar_),
            cloneNode(this._tuplePatternList_),
            cloneNode(this._rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATupleRawPattern(this);
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PTuplePatternList getTuplePatternList()
    {
        return this._tuplePatternList_;
    }

    public void setTuplePatternList(PTuplePatternList node)
    {
        if(this._tuplePatternList_ != null)
        {
            this._tuplePatternList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tuplePatternList_ = node;
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lPar_)
            + toString(this._tuplePatternList_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._tuplePatternList_ == child)
        {
            this._tuplePatternList_ = null;
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._tuplePatternList_ == oldChild)
        {
            setTuplePatternList((PTuplePatternList) newChild);
            return;
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
