/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import java.util.*;
import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ATuplePatternList extends PTuplePatternList
{
    private final LinkedList<PTuplePatternListHead> _tuplePatternListHead_ = new LinkedList<PTuplePatternListHead>();
    private PPattern _pattern_;

    public ATuplePatternList()
    {
        // Constructor
    }

    public ATuplePatternList(
        @SuppressWarnings("hiding") List<?> _tuplePatternListHead_,
        @SuppressWarnings("hiding") PPattern _pattern_)
    {
        // Constructor
        setTuplePatternListHead(_tuplePatternListHead_);

        setPattern(_pattern_);

    }

    @Override
    public Object clone()
    {
        return new ATuplePatternList(
            cloneList(this._tuplePatternListHead_),
            cloneNode(this._pattern_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATuplePatternList(this);
    }

    public LinkedList<PTuplePatternListHead> getTuplePatternListHead()
    {
        return this._tuplePatternListHead_;
    }

    public void setTuplePatternListHead(List<?> list)
    {
        for(PTuplePatternListHead e : this._tuplePatternListHead_)
        {
            e.parent(null);
        }
        this._tuplePatternListHead_.clear();

        for(Object obj_e : list)
        {
            PTuplePatternListHead e = (PTuplePatternListHead) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._tuplePatternListHead_.add(e);
        }
    }

    public PPattern getPattern()
    {
        return this._pattern_;
    }

    public void setPattern(PPattern node)
    {
        if(this._pattern_ != null)
        {
            this._pattern_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pattern_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tuplePatternListHead_)
            + toString(this._pattern_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tuplePatternListHead_.remove(child))
        {
            return;
        }

        if(this._pattern_ == child)
        {
            this._pattern_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PTuplePatternListHead> i = this._tuplePatternListHead_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTuplePatternListHead) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._pattern_ == oldChild)
        {
            setPattern((PPattern) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
