/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class ATypeAliasDefinitionStaticSection extends PStaticSection
{
    private PTypeAliasDefinition _typeAliasDefinition_;

    public ATypeAliasDefinitionStaticSection()
    {
        // Constructor
    }

    public ATypeAliasDefinitionStaticSection(
        @SuppressWarnings("hiding") PTypeAliasDefinition _typeAliasDefinition_)
    {
        // Constructor
        setTypeAliasDefinition(_typeAliasDefinition_);

    }

    @Override
    public Object clone()
    {
        return new ATypeAliasDefinitionStaticSection(
            cloneNode(this._typeAliasDefinition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeAliasDefinitionStaticSection(this);
    }

    public PTypeAliasDefinition getTypeAliasDefinition()
    {
        return this._typeAliasDefinition_;
    }

    public void setTypeAliasDefinition(PTypeAliasDefinition node)
    {
        if(this._typeAliasDefinition_ != null)
        {
            this._typeAliasDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeAliasDefinition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeAliasDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeAliasDefinition_ == child)
        {
            this._typeAliasDefinition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeAliasDefinition_ == oldChild)
        {
            setTypeAliasDefinition((PTypeAliasDefinition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
