/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class AUseTreeListTail extends PUseTreeListTail
{
    private TComma _comma_;
    private PUseTree _useTree_;

    public AUseTreeListTail()
    {
        // Constructor
    }

    public AUseTreeListTail(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PUseTree _useTree_)
    {
        // Constructor
        setComma(_comma_);

        setUseTree(_useTree_);

    }

    @Override
    public Object clone()
    {
        return new AUseTreeListTail(
            cloneNode(this._comma_),
            cloneNode(this._useTree_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUseTreeListTail(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PUseTree getUseTree()
    {
        return this._useTree_;
    }

    public void setUseTree(PUseTree node)
    {
        if(this._useTree_ != null)
        {
            this._useTree_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._useTree_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._useTree_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._useTree_ == child)
        {
            this._useTree_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._useTree_ == oldChild)
        {
            setUseTree((PUseTree) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
