/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class TCircularLeftShiftEquals extends Token
{
    public TCircularLeftShiftEquals()
    {
        super.setText("<</=");
    }

    public TCircularLeftShiftEquals(int line, int pos)
    {
        super.setText("<</=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCircularLeftShiftEquals(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCircularLeftShiftEquals(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCircularLeftShiftEquals text.");
    }
}
