/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class TConditionalIterativeKeyword extends Token
{
    public TConditionalIterativeKeyword(String text)
    {
        setText(text);
    }

    public TConditionalIterativeKeyword(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TConditionalIterativeKeyword(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTConditionalIterativeKeyword(this);
    }
}
