/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class TMut extends Token
{
    public TMut()
    {
        super.setText("mut");
    }

    public TMut(int line, int pos)
    {
        super.setText("mut");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMut(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMut(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMut text.");
    }
}
