/* This file was generated by SableCC (http://www.sablecc.org/). */

package drlc.node;

import drlc.analysis.*;

@SuppressWarnings("nls")
public final class TStruct extends Token
{
    public TStruct()
    {
        super.setText("struct");
    }

    public TStruct(int line, int pos)
    {
        super.setText("struct");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStruct(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStruct(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStruct text.");
    }
}
